apiVersion: v1
kind: Service
metadata:
  name: head-service
spec:
  type: NodePort
  selector:
    app: my-app-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
    hostIP: 127.0.0.1
    hostPort: 8000
  
  
